### ISSUE TITLE
Design landing page

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/navigatoruf.org#1]
We will need to design a welcoming landing page for the new site. This should highly NaviGator through pictures, alongside some text. It could mention how we will be competing at the upcoming RobotX competition in Sarasota, and the affiliation of the ASV to MIL (with a link back to the MIL website).

Some example Tailwind landing sites can be found here! :)
https://templates.digizu.co.uk/

(my personal favorite is [essential](https://templates.digizu.co.uk/layouts/essential))

**Comment by cbrxyz** [comment]
@lynettehemingway @willzoo Do you guys feel comfortable to assign yourselves to this issue?

**Comment by lynettehemingway** [comment]
Yes, I can do it!

**Comment by willzoo** [comment]
Yes! but it seems I don't have permission to assign myself right now

**Comment by cbrxyz** [comment]
Can you guys try now?

**Comment by willzoo** [comment]
Yep it works now

**Comment by lynettehemingway** [comment]
here is my design using figma: https://www.figma.com/design/AHyxMgNixYfoqcv4V09JVK/NaviGator-Design?node-id=0-1&t=MVZQJHqwRv7lmfoP-1 lemme know if i should add or change anything

**Comment by willzoo** [comment]
LGTM but you might wanna check out https://robosub.org/programs/2024/ for inspiration. It has all the websites for the RoboSub competition teams this year and BRAC University's team was the one that won the web design competition.

**Comment by lynettehemingway** [comment]
Is this the website? https://bracurobu.org/#contact Also, feel free to edit anything! https://www.figma.com/design/AHyxMgNixYfoqcv4V09JVK/NaviGator-Design?node-id=0-1&t=gS2iULmfWVFZaLRc-1

**Comment by willzoo** [comment]
Yep! Thats the right website

**Comment by willzoo** [comment]
NVM actually this is the right website: https://bracu-duburi.com/

**Comment by willzoo** [comment]
Update: Mostly finished turning Lynette's Figma design into an HTML file, you can check it out by opening landing_page.html! Also have been working on the dock color detection issue and alerted Andrew to a bug with the AMV not moving in the sim (which he fixed).

**Comment by cbrxyz** [comment]
@willzoo Thanks for your work so far! It looks great! Also, when submitting changes, can you please use the [Pull Requests tab](https://github.com/uf-mil/navigatoruf.org/pulls) and look over our [contributing guidelines](https://mil.ufl.edu/docs/software/contributing.html)? No big deal or anything, just for next time! Thank you!!

**Comment by willzoo** [comment]
@cbrxyz Sorry😅I'll make a new branch and work in that from now on!

**Comment by cbrxyz** [comment]
Finished in [Lynette's Figma](https://www.figma.com/design/AHyxMgNixYfoqcv4V09JVK/NaviGator-Design?node-id=90-489&node-type=section&t=hlz0iNKrDqWXcDQe-0)
