### ISSUE TITLE
Design team page

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/navigatoruf.org#2]
Design a page that highlights our team members, their responsibilities, and their contributions to NaviGator. This page should include spaces for pictures of each lead, alongside a list of all team members who worked on NaviGator and their respective team. It could also include a list of responsibilities/contributions for each member.

**Comment by lynettehemingway** [comment]
attached is my design for the teams page! https://www.figma.com/design/AHyxMgNixYfoqcv4V09JVK/NaviGator-Design?node-id=0-1&t=fGl3jPEuc6oxlKBe-1

**Comment by cbrxyz** [comment]
Finished in [Lynette's Figma](https://www.figma.com/design/AHyxMgNixYfoqcv4V09JVK/NaviGator-Design?node-id=90-489&node-type=section&t=hlz0iNKrDqWXcDQe-0)
