### ISSUE TITLE
Design vehicle page

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/navigatoruf.org#3]
We will need to design a page that is focused on our vehicle and the engineering behind it. We should likely include a CAD model/picture of NaviGator, a list of its subsystems (with pictures for each), potentially a video of it working, a list of the papers published on NaviGator, and a reference to our simulation environment ([vrx](https://github.com/osrf/vrx)).

This page could also be broken up into separate pages per team (ie, a page on the mechanical workings, a page on the electrical workings, and a page on the software workings).

**Comment by willzoo** [comment]
![Vehicle Design Pages](https://github.com/user-attachments/assets/82e82488-0256-4238-b7ad-7d3f1a52b20c)
Update: Made a new Figma design for the main Vehicle page, and a separate design for the Mechanical, Software, and Electrical Design pages. They can all be viewed at the same link we've been using: https://www.figma.com/design/AHyxMgNixYfoqcv4V09JVK/NaviGator-Design?node-id=0-1&node-type=canvas&t=7CYygDwaWHrbsVLO-0 
According to the 2024 RobotX handbook, a large portion of website score comes from showing the Vehicle Development and Testing Process, which I think should be included as a timeline in the main vehicle design page (prototype of this is in the Figma).
Also have been helping out in the Dock and Deliver issue by writing a basic version of the find_color() function which detects the color of the dock, which I have committed to docking_2024.

**Comment by cbrxyz** [comment]
Finished in [Lynette and William's Figma](https://www.figma.com/design/AHyxMgNixYfoqcv4V09JVK/NaviGator-Design?node-id=90-489&node-type=section&t=hlz0iNKrDqWXcDQe-0)
