### ISSUE TITLE
Design photos page

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/navigatoruf.org#5]
We should add a page that focuses on some of the photos taken at testings and at each competition that NaviGator has competed at.

**Comment by lynettehemingway** [comment]
update: i worked on the sponsers and photos figma designs for the website. https://www.figma.com/design/AHyxMgNixYfoqcv4V09JVK/NaviGator-Design?node-id=90-489&node-type=section&t=hlz0iNKrDqWXcDQe-0

**Comment by cbrxyz** [comment]
@lynettehemingway Thanks for all of your hard work! We can now start building the actual implementations for each page, based on your initial designs.

**Comment by cbrxyz** [comment]
Finished in [Lynette and William's Figma](https://www.figma.com/design/AHyxMgNixYfoqcv4V09JVK/NaviGator-Design?node-id=90-489&node-type=section&t=hlz0iNKrDqWXcDQe-0)

**Comment by lynettehemingway** [comment]
> @lynettehemingway Thanks for all of your hard work! We can now start building the actual implementations for each page, based on your initial designs.

Thank you, no problem!!
