### ISSUE TITLE
Build team page

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/navigatoruf.org#8]
Going off of [Lynette's Figma](https://www.figma.com/design/AHyxMgNixYfoqcv4V09JVK/NaviGator-Design?node-id=90-489&node-type=section&t=hlz0iNKrDqWXcDQe-0), we will need to create the implementation of the team page.

This includes creating the HTML and opening a pull request with the changes for a lead to review.

**Comment by lynettehemingway** [comment]
Update: Started to work on implementing the team page. I was wondering if there is a spreadsheet of all the members and subsections. Thank you!
