### ISSUE TITLE
Build Vehicle Page

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/navigatoruf.org#9]
Going off of [Lynette and William's Figma](https://www.figma.com/design/AHyxMgNixYfoqcv4V09JVK/NaviGator-Design?node-id=90-489&node-type=section&t=hlz0iNKrDqWXcDQe-0), we will need to create the implementation of the vehicle page.

This includes creating the HTML and opening a pull request with the changes for a lead to review.

**Comment by willzoo** [comment]
![image](https://github.com/user-attachments/assets/0cc4993d-07d4-47c5-90fe-30bd656e5d94)
Update: Made a new branch for the vehicle page, and have started the HTML for it there. The top part with the vehicle info is functional. Also, for the header across all pages I think we should agree on a format, IMO we should stick with the Figma and have a dark filter over the background image.
